[package]
name = "ragequit"
description = "A blazingly fast drop-in replacement for the Mastodon streaming api server"
version = "0.1.0"
authors = ["Daniel Long Sockwell <daniel@codesections.com", "Julian Laubstein <contact@julianlaubstein.de>"]
edition = "2018"

[dependencies]
log = "0.4.6"
futures = "0.1.26"
tokio = "0.1.19"
warp = "0.1.15"
regex = "1.1.5"
serde_json = "1.0.39"
serde_derive = "1.0.90"
serde = "1.0.90"
pretty_env_logger = "0.3.0"
postgres = "0.15.2"
uuid = { version = "0.7", features = ["v4"] }
dotenv = "0.14.0"

[features]
default = [ "production" ]
production = []
